### ISSUE TITLE
Support Youtube "user" URL

### ISSUE THREAD

**Issue by kelson42** [kiwix/youtube#14]
A channel on Youtube can be access by two URLs, one using the "user" scheme and an other one using the "channel" scheme. For example:
* https://www.youtube.com/user/tedmed is same as
* https://www.youtube.com/channel/UC6Arrv8WD3Z2CehgFefCXTA

But youtube2zim only supports the "channel" typed URLs. This is not a really user-friendly as this can easily be forgotten by the user. It would be better to allow both.

This sounds to me feasible because both page in HTML contain the following node:

`<meta itemprop="channelId" content="UC6Arrv8WD3Z2CehgFefCXTA">
`

It would be then easy to use internaly the "channel" URL based on the "content" value....

**Comment by dattaz** [comment]
Same done
