### ISSUE TITLE
Script should skip video which need additional permission to be viewed

### ISSUE THREAD

**Issue by kelson42** [kiwix/youtube#4]
Because currently I'm blocked by downloading many channels, for example:
./youtube2zim.py https://www.youtube.com/user/TEDEducation eng Kiwix --dl-playlist

...

WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Downloading video 20 of 35
[youtube] 5pdYQSnfUh4: Downloading webpage
[youtube] 5pdYQSnfUh4: Downloading embed webpage
[youtube] 5pdYQSnfUh4: Refetching age-gated info webpage
ERROR: 5pdYQSnfUh4: YouTube said: Please sign in to view this video.
error : <class 'youtube_dl.utils.DownloadError'>
Error during getting list of video

**Comment by dattaz** [comment]
Issue come from this playlist https://www.youtube.com/playlist?list=PLJicmE8fK0EgLE9ab39Xb91zU2TVx7MY3

**Comment by kelson42** [comment]
@dattaz Pas de workaround possible? Pas possible de gérer ce type d'erreur? Ignorer?

**Comment by dattaz** [comment]
Par le commit b6c835a les videos pour lesquels il y a une erreur quand on récupère les infos sont ignorer.

**Comment by kelson42** [comment]
I have tested it.. but do you skip the whole playlist or just that video?

**Comment by dattaz** [comment]
with the last commit we just skip video

**Comment by kelson42** [comment]
Super! Merci!
