### ISSUE TITLE
Download directly in webm format if possible

### ISSUE THREAD

**Issue by kelson42** [kiwix/youtube#7]
New version of youtube/youtube-dl provide webm. If possible this version should be preferred to the mp4 version and this would avoid any re-encoding. This would be good, because that would speed up the whole process.

**Comment by dattaz** [comment]
already done with this commit https://github.com/kiwix/youtube/commit/3ff3a7f9180ef506f765febae87f2320b534d4fc no ? (see issue #3 )

**Comment by kelson42** [comment]
Oh, sorry... My fault.
