### ISSUE TITLE
Use if possible youtube-dl re-encoding feature

### ISSUE THREAD

**Issue by kelson42** [kiwix/youtube#9]
New version of youtube-dl provide a re-encoding feature which might (to be tested) be better configured than our custom re-encoding code. We should try to use it.

**Comment by dattaz** [comment]
They use ffmpeg as us

**Comment by dattaz** [comment]
I created a branch for this feature https://github.com/kiwix/youtube/tree/reencoding_by_youtubeDL (remove some function)
Maybe we should run a benchmark between them and see who is the best

**Comment by kelson42** [comment]
@dattaz Great, I will and come back to you.

**Comment by kelson42** [comment]
@dattaz 
After testing it looks like the youtube-dl encoding works well but still produce pretty large (and some use cases too large) video files.

That's why, to my opinion, we should provide:
* A default mode downloading the webm from youtube or using youtube-dl re-encoding from mp4 to webm if webm not available online
* A --lowquality option to re-encode (like currently) in "low' webm quality

Does that make sense?

**Comment by dattaz** [comment]
done in this branch  https://github.com/kiwix/youtube/tree/reencoding_by_youtubeDL 
The option name is --lowquality 
The README has be update
If it's ok for you, I will merge that in master.
